ktor:
    application:
        modules:
            - de.jkamue.ApplicationKt.module
    deployment:
        port: 8081

brokerish:
    maximumQualityOfService: AT_MOST_ONCE_DELIVERY
    keepAliveTimeoutMultiplier: 1.5 # Defined in 3.14.2.1 Table 3-10 Value 141 as default keep alive time